# Generated by Django 3.0.8 on 2020-07-07 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(db_index=True, max_length=64, verbose_name='Brand')),
                ('model', models.CharField(max_length=64, verbose_name='Model')),
                ('color', models.CharField(max_length=64, verbose_name='Color')),
                ('os', models.IntegerField(choices=[(1, 'Android'), (2, 'IOS')], verbose_name='OS')),
                ('phone_type', models.IntegerField(choices=[(1, 'Smartphone'), (2, 'Buttonphone'), (3, 'Clamshell')], verbose_name='Phone_Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
